# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23323b8124d182950b27df270b8103c1c66e403c97cf960c945112803b890d2b3d21dd234faa4ac9620b8e175e8708feff85f2f6e44fcf5afddcd318e8b06487

test:
  secret_key_base: 353eada53ba4ce332ca290733a81ee8f1f06207a64e7c0e110d88aa1595a38bb6af4ae06735c7b7e3c4a2e8ff196e8323ede9d74f4b5a0e3cce5475a655dab80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
